
@media (min-width: 200px) {
    .SecondCombinedChart{
        margin:1%  0px 00px 10px;
        width: 100%;
        display: flex;
     }
     .SecondCharts{
        width: 90%;
        height: 300px;
        margin-top:5%;
     }
     .firstchart{
        width: 93%;
        height: 160px;
     }
     .graphheadingFontSize{
        font-size: 15px;
        font-weight: 600;
  /* box-shadow: 3px 0px 0px 0px rgba(0, 0, 0, 0.2) ;
        border-radius: 10px 10px 0px 0px */
     }
     .firstSection{
        width: 100%;
     }
   
   }
   
   @media (min-width: 350px) {
     /* Medium screens and larger */
     .SecondCombinedChart{
        margin: 1%  0px 10px 10px;
        width: 100%;
        height:480px ;
        display: flex;
        flex-wrap: wrap;
     }
     .SecondCharts{
        width: 90%;
        height: 240px;
        margin-top: 5px;
     }
     .firstchart{
        width: 93%;
        height: 160px;
      
     }
     .graphheadingFontSize{
        font-size: 15px;
        font-weight: 600;
     }
     .firstSection{
        width: 100%;
     }
   }
   
   @media (min-width: 400px) {
     
     .firstSection{
        width: 100%;
     }
       
      
     }
   
   @media (min-width: 576px) {
    .SecondCombinedChart{
        display: flex;
        margin: 0px  0px 30px 10px;
        width: 100%;
        height: 196px;
        justify-content: space-between;
     }
     .firstSection{
        width: 100%;
     }
     .firstchart{
      width: 100%;
      height: 210px;
      margin: 35px 0px 0px 0px;
   }
      
     }
   
   @media (min-width: 768px) {
     /* Large screens and larger */
     .firstSection{
        width: 65%;
     }
     .firstchart{
      width: 100%;
      height: 210px;
      margin: 35px 0px 0px 0px;
   }
    
   }
   
   @media (min-width: 950px) {
     /* Medium screens and larger */
     .SecondCombinedChart{
        display: flex;
        margin: 1%  0px 30px 10px;
        width: 99%;
        height: 250px;
        justify-content: space-between;
     }

     .SecondCharts{
        width: 48%;
        height: 100%;
        margin-top: 0px;
     }
     .firstchart{
        width: 100%;
        height: 210px;
        margin: 35px 0px 0px 0px;
     }
     .graphheadingFontSize{
        font-size: 20px;
        font-weight: 600;
     }
     .firstSection{
        width:90%;
     }
   }
   